[package]
name = "project"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4", features = ["unstable-locales"] }
exacl = "0.12.0"
git2 = "0.20.2"
users = "0.11.0"
libc = "0.2"
